apiVersion: v1
kind: Service
metadata:
  name: client-portal-be
  namespace: client-portal
  labels:
    app.kubernetes.io/name: client-portal-be
    app.kubernetes.io/part-of: client-portal
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: client-portal-be
    app.kubernetes.io/part-of: client-portal
    app.kubernetes.io/component: backend
  ports:
    - name: http
      port: 80
      targetPort: 8000
